name: DEV - Build & Deploy
on:
 push:
   branches:
     - dev
jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       dir: ['./backend/functions','./frontend']
       node-version: [10.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - name: Install Packages
     run: npm install
     working-directory: ${{ matrix.dir }}
   - name: Build project
     run: npm build
     working-directory: ${{ matrix.dir }}
   - name: Upload production-ready build files
     uses: actions/upload-artifact@v2
     with:
       name: production-files
       path: ./build
 deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
