name: DEV - Build
on:
 push:
   branches:
     - dev
jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       dir: ['./backend/functions','./frontend']
       node-version: [14.x]
   steps:
   - uses: actions/checkout@v2

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v2
     with:
       node-version: ${{ matrix.node-version }}
       
   - uses: expo/expo-github-action@v5
     with:
       expo-version: 4.x
       expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
       expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
       expo-cache: true
       
   - name: Install Packages
     run: npm install
     working-directory: ${{ matrix.dir }}
   
   - name: Install Expo
     run: npm install --global expo-cli
     working-directory: './frontend'
     
   - name: Build project backend
     run: npm run build
     working-directory: './backend/functions'
     
   - name: Build project frontend
     run: expo publish --release-channel production
     working-directory: './frontend'
     
   - name: Upload production-ready build files
     uses: actions/upload-artifact@v2
     with:
       name: production-files
       path: ./build
