name: DEV - Build
on:
 push:
   branches:
     - dev
jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   strategy:
     matrix: 
       dir: ['./backend/functions','./frontend']
       node-version: [10.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - name: Install Packages
     run: npm install
     working-directory: ${{ matrix.dir }}
     
   - name: Build project Back
     run: npm run build
     working-directory: './backend/functions'
     
   - name: Build project Front
     run: npm build
     working-directory: './frontend'
     
   - name: Upload production-ready build files
     uses: actions/upload-artifact@v2
     with:
       name: production-files
       path: ./build
