name: DEV (pullrequest) - Build
on:
 pull_request:
   branches:
     - dev
jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [10.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - name: Install Packages
     run: npm install
     working-directory: ./backend/functions
   - name: Build project
     run: npm build
     working-directory: ./backend/functions
   - name: Upload production-ready build files
     uses: actions/upload-artifact@v2
     with:
       name: production-files
       path: ./build
